### PR TITLE
ipxe: Enable serial output

### PR DESCRIPTION
**Pull request by tfc**
@parthy this should be it, right?

### CODE REVIEW

**Comment by parthy** [comment]
It should. Does it work?

**Comment by blitz** [comment]
@parthy @tfc Is this PR still relevant?

**Comment by kaldonir** [comment]
Would this only work for native serial?

**Comment by parthy** [comment]
> Would this only work for native serial?

Worse. It only works for the hardcoded serial port in `serial.h`, which is `COM1` by default. So it only works for machines where the serial port you're listening on is connected to the physical port with the port number `0x3f8`.

**Comment by blitz** [comment]
@tfc ping?

**Pull request closed without merging**
